### ISSUE TITLE
Programs and Services - The page is unpublished but still visible on both the site and menu

### ISSUE THREAD

**Issue by tgascoigne14** [CCI-Studios/Bluewater-Health#31]

**Comment by ccmorris** [comment]
I did set up these pages correctly, I think. You can see the pages and menu items if you are logged in as an administrator since you have the permissions to view it.

For example, Palliative Care (http://bwh.ccistaging.com/programs-and-services/palliative-care) is not accessible or visible if you are not logged in.

**Comment by tgascoigne14** [comment]
This is correct. I signed out and those pages were no longer visible
